-- Seed data for Deep-Shiva Database
-- This file contains sample data to populate the database for testing and development

-- Insert sample users
INSERT INTO users (username, email, full_name, preferred_language, location, interests) VALUES
('john_traveler', 'john@example.com', 'John Smith', 'en', 'Delhi', '["adventure", "temples", "trekking"]'),
('priya_explorer', 'priya@example.com', 'Priya Sharma', 'hi', 'Mumbai', '["culture", "yoga", "photography"]'),
('mike_adventurer', 'mike@example.com', 'Mike Johnson', 'en', 'Bangalore', '["wildlife", "mountains", "spirituality"]'),
('anita_yogi', 'anita@example.com', 'Anita Gupta', 'hi', 'Haridwar', '["yoga", "meditation", "wellness"]'),
('david_photographer', 'david@example.com', 'David Wilson', 'en', 'London', '["photography", "heritage", "nature"]');

-- Insert sample cultural sites
INSERT INTO cultural_sites (name, description, location, district, latitude, longitude, category, historical_significance, visiting_hours, entry_fee, best_time_to_visit, images) VALUES
('Kedarnath Temple', 'One of the twelve Jyotirlingas dedicated to Lord Shiva', 'Kedarnath', 'Rudraprayag', 30.7346, 79.0669, 'temple', 'Ancient temple mentioned in Puranas, rebuilt after 2013 floods', '4:00 AM - 9:00 PM', 'Free', 'May to October', '["kedarnath1.jpg", "kedarnath2.jpg"]'),
('Badrinath Temple', 'Sacred Hindu temple dedicated to Lord Vishnu', 'Badrinath', 'Chamoli', 30.7433, 79.4938, 'temple', 'One of the Char Dham pilgrimage sites', '4:30 AM - 1:00 PM, 4:00 PM - 9:00 PM', 'Free', 'May to October', '["badrinath1.jpg", "badrinath2.jpg"]'),
('Haridwar Ghats', 'Sacred ghats on the banks of River Ganga', 'Haridwar', 'Haridwar', 29.9457, 78.1642, 'heritage', 'Ancient pilgrimage site where Ganga enters plains', '24 hours', 'Free', 'October to March', '["haridwar1.jpg", "haridwar2.jpg"]'),
('Rishikesh Ashrams', 'Spiritual center with numerous ashrams and temples', 'Rishikesh', 'Dehradun', 30.0869, 78.2676, 'heritage', 'Yoga capital of the world, Beatles connection', '5:00 AM - 10:00 PM', 'Free', 'October to March', '["rishikesh1.jpg", "rishikesh2.jpg"]'),
('Jageshwar Temple Complex', 'Group of 124 ancient stone temples', 'Jageshwar', 'Almora', 29.6389, 79.8472, 'temple', 'Dating back to 9th-13th century CE', '6:00 AM - 8:00 PM', 'Free', 'March to June, September to November', '["jageshwar1.jpg", "jageshwar2.jpg"]');

-- Insert sample cultural traditions
INSERT INTO cultural_traditions (name, description, district, category, origin_story, significance, when_practiced, participants, materials_required, steps_or_process, cultural_values, modern_relevance, preservation_status, images) VALUES
('Kumaoni Folk Dance (Chholiya)', 'Traditional sword dance performed during weddings and festivals', 'Almora', 'dance', 'Originated from the martial traditions of Kumaon region, performed by warriors', 'Represents valor, protection, and celebration of life events', 'Weddings, festivals like Diwali and Holi', 'Men of all ages, traditionally performed by grooms party', '["swords", "traditional_dhoti", "turban", "drums"]', '["formation_in_circle", "rhythmic_sword_movements", "synchronized_steps", "call_and_response_singing"]', '["courage", "community_bonding", "celebration", "heritage_preservation"]', 'Still performed at weddings, cultural events, and tourism shows', 'active', '["chholiya1.jpg", "chholiya2.jpg"]'),
('Garhwali Langvir Nritya', 'Acrobatic folk dance where performers balance on bamboo poles', 'Tehri Garhwal', 'dance', 'Ancient tradition showcasing physical prowess and spiritual devotion', 'Demonstrates human potential and connection with divine through physical mastery', 'Religious festivals, especially during Navratri', 'Young men trained in acrobatics', '["bamboo_poles", "traditional_costume", "dhol", "damau"]', '["pole_setup", "climbing_technique", "balancing_acts", "aerial_movements", "group_coordination"]', '["discipline", "devotion", "physical_fitness", "fearlessness"]', 'Performed at cultural festivals and attracts tourists', 'active', '["langvir1.jpg", "langvir2.jpg"]'),
('Jagar (Spirit Calling Ritual)', 'Traditional ritual to invoke local deities and spirits', 'Kumaon and Garhwal', 'ritual', 'Ancient shamanic practice connecting communities with local deities', 'Healing, problem-solving, and maintaining spiritual balance in community', 'During illness, community problems, or festivals', 'Jagari (medium), musicians, community members', '["dhol", "damau", "thali", "rice", "flowers", "incense"]', '["preparation_of_sacred_space", "invocation_chants", "rhythmic_drumming", "spirit_possession", "divine_guidance"]', '["spiritual_healing", "community_support", "ancestral_wisdom", "problem_resolution"]', 'Still practiced in villages for healing and guidance', 'active', '["jagar1.jpg", "jagar2.jpg"]'),
('Basant Panchami Celebration', 'Spring festival celebrating knowledge, arts, and new beginnings', 'All districts', 'festival', 'Ancient celebration of Goddess Saraswati and arrival of spring', 'Worship of knowledge, arts, and cultural learning', 'Basant Panchami day (January-February)', 'All community members, especially students and artists', '["yellow_clothes", "flowers", "books", "musical_instruments", "sweets"]', '["morning_prayers", "cultural_programs", "kite_flying", "community_feast", "artistic_competitions"]', '["education", "creativity", "seasonal_harmony", "community_celebration"]', 'Celebrated in schools, colleges, and cultural centers', 'active', '["basant1.jpg", "basant2.jpg"]'),
('Traditional Kumaoni Cuisine Preparation', 'Authentic cooking methods and recipes passed through generations', 'Kumaon region', 'cuisine', 'Developed from local ingredients and seasonal availability', 'Preserves nutritional wisdom and cultural identity through food', 'Daily cooking, festivals, special occasions', 'Women of all ages, increasingly men too', '["traditional_utensils", "local_spices", "seasonal_vegetables", "grains"]', '["ingredient_selection", "traditional_cooking_methods", "seasoning_techniques", "presentation_styles"]', '["health_consciousness", "sustainability", "family_bonding", "cultural_continuity"]', 'Growing interest in organic and traditional cooking', 'active', '["cuisine1.jpg", "cuisine2.jpg"]');

-- Insert sample cultural practitioners
INSERT INTO cultural_practitioners (name, email, phone, location, district, specialization, experience_years, description, teaching_available, languages_spoken, achievements, availability_schedule, contact_preference, is_verified) VALUES
('Mohan Singh Rawat', 'mohan.rawat@example.com', '+91-9876543210', 'Almora', 'Almora', '["Chholiya_dance", "traditional_music", "folk_singing"]', 35, 'Master performer and teacher of Kumaoni folk arts, has performed internationally', true, '["Hindi", "Kumaoni", "English"]', '["Padma_Shri_nominee", "Cultural_Ambassador_UK_2019", "50_years_teaching"]', '{"weekdays": "evening", "weekends": "full_day", "festivals": "available"}', 'phone', true),
('Kamala Bisht', 'kamala.bisht@example.com', '+91-9876543211', 'Bageshwar', 'Bageshwar', '["traditional_cooking", "folk_songs", "storytelling"]', 28, 'Expert in traditional Kumaoni cuisine and cultural storytelling', true, '["Hindi", "Kumaoni"]', '["Best_Traditional_Cook_2020", "Cultural_Heritage_Award"]', '{"mornings": "available", "evenings": "cooking_classes"}', 'phone', true),
('Jagat Singh Negi', 'jagat.negi@example.com', '+91-9876543212', 'Tehri', 'Tehri Garhwal', '["Langvir_Nritya", "acrobatics", "traditional_instruments"]', 22, 'Young master of Langvir Nritya, training next generation', true, '["Hindi", "Garhwali", "English"]', '["State_Youth_Award_2021", "International_Folk_Festival_performer"]', '{"weekends": "workshops", "evenings": "training"}', 'whatsapp', true),
('Devi Datt Joshi', 'devi.joshi@example.com', '+91-9876543213', 'Pithoragarh', 'Pithoragarh', '["Jagar_ritual", "spiritual_healing", "traditional_chants"]', 45, 'Experienced Jagari (spiritual medium) and healer', false, '["Hindi", "Kumaoni", "Sanskrit"]', '["Community_Healer_Recognition", "40_years_practice"]', '{"on_request": "spiritual_sessions"}', 'phone', true),
('Sunita Pandey', 'sunita.pandey@example.com', '+91-9876543214', 'Pauri', 'Pauri Garhwal', '["folk_dance", "cultural_education", "youth_training"]', 18, 'Cultural educator specializing in youth programs and folk dance', true, '["Hindi", "Garhwali", "English"]', '["Best_Cultural_Teacher_2022", "Youth_Mentor_Award"]', '{"weekdays": "school_programs", "weekends": "community_workshops"}', 'email', true);

-- Insert sample cultural events
INSERT INTO cultural_events (title, description, event_type, tradition_id, organizer, location, district, start_date, end_date, registration_required, registration_fee, max_participants, age_group, skill_level, contact_info, requirements, learning_outcomes, images, status) VALUES
('Kumaoni Folk Dance Workshop', 'Learn traditional Chholiya dance with master performers', 'workshop', 1, 'Uttarakhand Cultural Society', 'Community Center, Almora', 'Almora', '2024-03-15 10:00:00+05:30', '2024-03-17 17:00:00+05:30', true, 500.00, 30, '15-50 years', 'beginner', '{"phone": "+91-9876543210", "email": "info@ukculture.org"}', '["comfortable_clothing", "water_bottle", "enthusiasm_to_learn"]', '["basic_dance_steps", "cultural_understanding", "performance_confidence"]', '["workshop1.jpg", "workshop2.jpg"]', 'upcoming'),
('Traditional Cooking Masterclass', 'Learn authentic Kumaoni recipes and cooking techniques', 'workshop', 5, 'Himalayan Culinary Institute', 'Cooking Studio, Nainital', 'Nainital', '2024-03-20 09:00:00+05:30', '2024-03-22 16:00:00+05:30', true, 1200.00, 20, '18+ years', 'all', '{"phone": "+91-9876543211", "email": "cook@himalayan.org"}', '["apron", "notebook", "basic_cooking_knowledge"]', '["traditional_recipes", "cooking_techniques", "cultural_food_significance"]', '["cooking1.jpg", "cooking2.jpg"]', 'upcoming'),
('Basant Panchami Cultural Festival', 'Community celebration with cultural performances and competitions', 'festival', 4, 'District Cultural Committee', 'Town Square, Dehradun', 'Dehradun', '2024-02-14 08:00:00+05:30', '2024-02-14 20:00:00+05:30', false, 0.00, 1000, 'All ages', 'all', '{"phone": "+91-135-2711111", "email": "culture@dehradun.gov.in"}', '["yellow_clothing_preferred", "participation_enthusiasm"]', '["cultural_appreciation", "community_bonding", "artistic_exposure"]', '["festival1.jpg", "festival2.jpg"]', 'upcoming'),


-- Insert sample artisans (for cultural preservation context)
INSERT INTO artisans (name, email, phone, location, district, specialization, experience_years, description, profile_image, is_verified) VALUES
('Ram Singh Bisht', 'ram.bisht@example.com', '+91-9876543210', 'Almora', 'Almora', 'woodwork', 25, 'Master craftsman specializing in traditional Kumaoni wood carving and cultural preservation', 'ram_bisht.jpg', true),
('Kamala Devi', 'kamala.devi@example.com', '+91-9876543211', 'Bageshwar', 'Bageshwar', 'textiles', 18, 'Expert in traditional Kumaoni weaving, embroidery, and textile heritage', 'kamala_devi.jpg', true),
('Mohan Lal Joshi', 'mohan.joshi@example.com', '+91-9876543212', 'Pithoragarh', 'Pithoragarh', 'pottery', 30, 'Traditional potter preserving authentic Kumaoni clay craft techniques', 'mohan_joshi.jpg', true),
('Sunita Rawat', 'sunita.rawat@example.com', '+91-9876543213', 'Champawat', 'Champawat', 'jewelry', 15, 'Artisan preserving traditional silver jewelry making with local cultural motifs', 'sunita_rawat.jpg', false),
('Dhan Singh Negi', 'dhan.negi@example.com', '+91-9876543214', 'Tehri Garhwal', 'Tehri Garhwal', 'metalwork', 22, 'Skilled metalworker preserving traditional brass and copper craft heritage', 'dhan_negi.jpg', true);

-- Insert sample artisan products (for cultural documentation, not commercial)
INSERT INTO artisan_products (artisan_id, name, description, category, price, materials_used, dimensions, weight, images, availability_status) VALUES
(1, 'Traditional Wooden Mask', 'Hand-carved wooden mask used in local folk dances - cultural artifact', 'cultural_artifact', 0.00, 'Deodar wood, natural colors', '25cm x 20cm', '300g', '["mask1.jpg", "mask2.jpg"]', 'display_only'),
(1, 'Kumaoni Wooden Box', 'Intricately carved storage box with traditional motifs - heritage craft', 'cultural_artifact', 0.00, 'Walnut wood, brass fittings', '30cm x 20cm x 15cm', '800g', '["box1.jpg", "box2.jpg"]', 'display_only'),
(2, 'Traditional Handwoven Shawl', 'Traditional Kumaoni shawl with geometric patterns - textile heritage', 'cultural_artifact', 0.00, 'Pure wool, natural dyes', '200cm x 100cm', '400g', '["shawl1.jpg", "shawl2.jpg"]', 'display_only'),
(2, 'Embroidered Wall Hanging', 'Beautiful wall hanging with traditional Kumaoni embroidery - cultural art', 'cultural_artifact', 0.00, 'Cotton fabric, silk threads', '60cm x 40cm', '200g', '["hanging1.jpg", "hanging2.jpg"]', 'display_only'),
(3, 'Traditional Clay Water Pot', 'Traditional clay pot for storing and cooling water - heritage utility', 'cultural_artifact', 0.00, 'Local clay, natural finish', '25cm diameter', '1.2kg', '["pot1.jpg", "pot2.jpg"]', 'display_only'),
(3, 'Decorative Clay Lamp', 'Hand-shaped clay lamp for festivals and ceremonies - cultural item', 'cultural_artifact', 0.00, 'Terracotta clay, natural colors', '10cm x 8cm', '150g', '["lamp1.jpg", "lamp2.jpg"]', 'display_only'),
(4, 'Traditional Silver Nose Ring', 'Traditional Kumaoni nose ring with intricate design - cultural jewelry', 'cultural_artifact', 0.00, 'Pure silver, traditional craftsmanship', '2cm diameter', '5g', '["nosering1.jpg", "nosering2.jpg"]', 'display_only'),
(4, 'Temple Jewelry Set', 'Complete set of traditional temple jewelry - heritage collection', 'cultural_artifact', 0.00, 'Silver, semi-precious stones', 'Various sizes', '150g', '["jewelry1.jpg", "jewelry2.jpg"]', 'display_only'),
(5, 'Brass Prayer Plate', 'Traditional brass plate used in religious ceremonies - ritual artifact', 'cultural_artifact', 0.00, 'Pure brass, hand-engraved', '20cm diameter', '400g', '["plate1.jpg", "plate2.jpg"]', 'display_only'),
(5, 'Copper Water Vessel', 'Traditional copper vessel for storing drinking water - heritage utility', 'cultural_artifact', 0.00, 'Pure copper, traditional design', '15cm x 25cm', '600g', '["vessel1.jpg", "vessel2.jpg"]', 'display_only');
('Langvir Nritya Training Camp', 'Intensive training in traditional acrobatic dance', 'workshop', 2, 'Garhwal Folk Arts Academy', 'Sports Complex, Tehri', 'Tehri Garhwal', '2024-04-01 06:00:00+05:30', '2024-04-07 18:00:00+05:30', true, 2000.00, 15, '16-30 years', 'intermediate', '{"phone": "+91-9876543212", "whatsapp": "+91-9876543212"}', '["physical_fitness", "medical_clearance", "sports_clothing", "insurance"]', '["acrobatic_skills", "traditional_dance", "physical_discipline", "cultural_pride"]', '["training1.jpg", "training2.jpg"]', 'upcoming'),
('Storytelling and Folklore Evening', 'Traditional stories and legends of Uttarakhand', 'performance', null, 'Heritage Preservation Society', 'Library Auditorium, Almora', 'Almora', '2024-03-25 18:00:00+05:30', '2024-03-25 21:00:00+05:30', false, 0.00, 100, 'All ages', 'all', '{"phone": "+91-9876543213", "email": "stories@heritage.org"}', '["interest_in_folklore", "comfortable_seating"]', '["cultural_stories", "historical_knowledge", "oral_tradition_appreciation"]', '["storytelling1.jpg", "storytelling2.jpg"]', 'upcoming');

-- Insert sample tourism places
INSERT INTO tourism_places (name, description, location, district, latitude, longitude, category, altitude, best_time_to_visit, activities, accommodation_options, transportation, entry_fee, images, crowd_level) VALUES
('Valley of Flowers', 'UNESCO World Heritage site known for endemic alpine flowers', 'Chamoli', 'Chamoli', 30.7268, 79.6034, 'national_park', 3658, 'July to September', '["trekking", "photography", "nature_walk"]', '["camping", "guest_houses_in_joshimath"]', 'Trek from Govindghat via Ghangaria', '₹150 for Indians, ₹600 for foreigners', '["valley1.jpg", "valley2.jpg"]', 'moderate'),
('Nainital Lake', 'Beautiful hill station centered around a natural lake', 'Nainital', 'Nainital', 29.3919, 79.4542, 'hill_station', 2084, 'March to June, September to November', '["boating", "shopping", "cable_car", "trekking"]', '["hotels", "resorts", "guest_houses"]', 'Road connectivity from Delhi, nearest railway Kathgodam', 'Free', '["nainital1.jpg", "nainital2.jpg"]', 'high'),
('Jim Corbett National Park', 'India''s oldest national park, famous for Bengal tigers', 'Ramnagar', 'Nainital', 29.5316, 78.9463, 'wildlife', 400, 'November to June', '["safari", "wildlife_photography", "bird_watching"]', '["forest_lodges", "resorts", "hotels"]', 'Road from Delhi, railway station Ramnagar', '₹200-1500 depending on zone', '["corbett1.jpg", "corbett2.jpg"]', 'moderate'),
('Auli Ski Resort', 'Popular skiing destination with panoramic Himalayan views', 'Auli', 'Chamoli', 30.5200, 79.5370, 'adventure', 2800, 'December to March for skiing, April to November for sightseeing', '["skiing", "cable_car", "trekking", "camping"]', '["ski_resorts", "government_guest_house", "camping"]', 'Road to Joshimath then cable car or trek', '₹50 entry, skiing charges separate', '["auli1.jpg", "auli2.jpg"]', 'moderate'),
('Mussoorie', 'Queen of Hills, popular hill station with colonial charm', 'Mussoorie', 'Dehradun', 30.4598, 78.0664, 'hill_station', 1880, 'April to June, September to November', '["mall_road_walk", "cable_car", "waterfall_visit", "trekking"]', '["hotels", "resorts", "homestays"]', 'Road from Dehradun, nearest railway Dehradun', 'Free', '["mussoorie1.jpg", "mussoorie2.jpg"]', 'high');

-- Insert sample yoga poses
INSERT INTO yoga_poses (name, sanskrit_name, description, difficulty_level, category, benefits, instructions, precautions, duration, image_url) VALUES
('Mountain Pose', 'Tadasana', 'Basic standing pose that forms foundation for other poses', 'beginner', 'standing', '["improves_posture", "strengthens_legs", "increases_awareness"]', '["Stand with feet hip-width apart", "Distribute weight evenly", "Engage leg muscles", "Lengthen spine", "Relax shoulders"]', 'Avoid if you have low blood pressure', '1-2 minutes', 'tadasana.jpg'),
('Downward Dog', 'Adho Mukha Svanasana', 'Inverted V-shape pose that stretches and strengthens whole body', 'beginner', 'inversion', '["stretches_hamstrings", "strengthens_arms", "improves_circulation"]', '["Start on hands and knees", "Tuck toes under", "Lift hips up and back", "Straighten legs", "Press hands firmly"]', 'Avoid if you have wrist injuries or high blood pressure', '1-3 minutes', 'downward_dog.jpg'),
('Warrior I', 'Virabhadrasana I', 'Standing pose that builds strength and stability', 'intermediate', 'standing', '["strengthens_legs", "opens_hips", "improves_balance"]', '["Step left foot back 3-4 feet", "Turn left foot out 45 degrees", "Bend right knee over ankle", "Raise arms overhead", "Hold and repeat other side"]', 'Avoid if you have knee or hip injuries', '30 seconds to 1 minute each side', 'warrior1.jpg'),
('Tree Pose', 'Vrikshasana', 'Balancing pose that improves focus and stability', 'intermediate', 'balancing', '["improves_balance", "strengthens_legs", "increases_focus"]', '["Stand on left foot", "Place right foot on inner left thigh", "Press foot into leg, leg into foot", "Bring palms together at heart", "Hold and switch sides"]', 'Avoid placing foot on side of knee', '30 seconds to 1 minute each side', 'tree_pose.jpg'),
('Child''s Pose', 'Balasana', 'Resting pose that calms mind and stretches back', 'beginner', 'resting', '["calms_nervous_system", "stretches_back", "relieves_stress"]', '["Kneel on floor", "Touch big toes together", "Sit back on heels", "Fold forward with arms extended", "Rest forehead on ground"]', 'Avoid if you have knee injuries', '1-5 minutes', 'childs_pose.jpg');

-- Insert sample emergency contacts
INSERT INTO emergency_contacts (district, service_type, name, phone_number, address, is_24x7) VALUES
('Dehradun', 'police', 'Dehradun Police Control Room', '100', 'Police Lines, Dehradun', true),
('Dehradun', 'hospital', 'Doon Hospital', '0135-2711308', 'Banarsidas Purohit Marg, Dehradun', true),
('Dehradun', 'fire', 'Fire Department Dehradun', '101', 'Fire Station, Rajpur Road, Dehradun', true),
('Dehradun', 'tourist_helpline', 'Uttarakhand Tourism Helpline', '1364', 'Tourism Office, Dehradun', true),
('Haridwar', 'police', 'Haridwar Police Station', '01334-265308', 'Civil Lines, Haridwar', true),
('Haridwar', 'hospital', 'Shri Guru Ram Rai Institute', '01334-286286', 'Patel Nagar, Haridwar', true),
('Rishikesh', 'police', 'Rishikesh Police Station', '0135-2430226', 'Rishikesh, Dehradun', true),
('Rishikesh', 'hospital', 'AIIMS Rishikesh', '0135-2462042', 'Virbhadra Road, Rishikesh', true),
('Nainital', 'police', 'Nainital Police Station', '05942-235355', 'The Mall, Nainital', true),
('Nainital', 'hospital', 'BD Pandey Hospital', '05942-235391', 'Ramgarh Road, Nainital', true),
('Almora', 'police', 'Almora Police Station', '05962-230424', 'Mall Road, Almora', true),
('Almora', 'hospital', 'District Hospital Almora', '05962-230424', 'Hospital Road, Almora', true);

-- Insert sample dashboard metrics
INSERT INTO dashboard_metrics (metric_name, metric_value, metric_type, category, additional_data) VALUES
('Total Users', 1247, 'count', 'users', '{"growth_rate": "15%", "new_this_month": 187}'),
('Active Chats Today', 3456, 'count', 'chats', '{"peak_hour": "2-4 PM", "avg_duration": "12 minutes"}'),
('Cultural Sites Listed', 156, 'count', 'culture', '{"verified": 142, "pending": 14}'),
('Cultural Practitioners', 89, 'count', 'culture', '{"verified": 67, "teaching_available": 45}'),
('Cultural Traditions', 25, 'count', 'culture', '{"active": 20, "declining": 3, "revived": 2}'),
('Cultural Events', 12, 'count', 'culture', '{"upcoming": 8, "ongoing": 2, "completed": 2}'),
('Tourism Places', 234, 'count', 'tourism', '{"hill_stations": 45, "temples": 78, "adventure": 56, "wildlife": 23, "heritage": 32}'),
('User Satisfaction', 4.6, 'rating', 'users', '{"total_reviews": 892, "5_star": 634, "4_star": 178}'),
('Chat Response Time', 1.2, 'seconds', 'chats', '{"avg_processing": "0.8s", "avg_ai_response": "0.4s"}'),
('Popular Features Usage', 45, 'percentage', 'chats', '{"chat": 45, "pose_analysis": 25, "tourism": 20, "culture": 10}'),
('Emergency Contacts', 48, 'count', 'emergency', '{"police": 13, "hospitals": 15, "fire": 13, "tourist_helpline": 7}'),
('Yoga Poses Database', 127, 'count', 'yoga', '{"beginner": 45, "intermediate": 52, "advanced": 30}');

-- Insert sample chats with enhanced metadata
INSERT INTO chats (user_id, title, chat_type, chat_metadata, message_count, total_tokens, avg_response_time, user_rating, tags, is_favorite, last_activity) VALUES
(1, 'Planning Kedarnath Trip', 'tourism', '{"location": "Delhi", "travel_dates": "2024-05-15 to 2024-05-20", "group_size": 4, "budget": "moderate"}', 8, 1250, 2.3, 5, '["pilgrimage", "trekking", "may_travel"]', true, '2024-01-15 14:30:00+05:30'),
(2, 'Yoga Poses for Beginners', 'yoga', '{"experience_level": "beginner", "health_conditions": "none", "preferred_time": "morning", "goals": ["flexibility", "stress_relief"]}', 12, 980, 1.8, 4, '["beginner", "morning_routine", "flexibility"]', false, '2024-01-14 09:15:00+05:30'),
(3, 'Cultural Traditions Learning', 'culture', '{"interests": ["dance", "music", "festivals"], "location": "Almora", "learning_purpose": "cultural_preservation"}', 15, 1450, 2.1, 5, '["folk_dance", "cultural_learning", "almora"]', true, '2024-01-16 16:45:00+05:30'),
(4, 'Emergency Contacts Haridwar', 'emergency', '{"location": "Haridwar", "emergency_type": "medical", "urgency": "medium"}', 3, 320, 0.9, 4, '["emergency", "medical", "haridwar"]', false, '2024-01-13 11:20:00+05:30'),
(5, 'Photography Spots Guide', 'general', '{"photography_type": "landscape", "equipment": "DSLR", "season": "winter", "skill_level": "intermediate"}', 20, 2100, 2.5, 5, '["photography", "landscape", "winter"]', true, '2024-01-16 18:00:00+05:30');

-- Insert sample chat messages with enhanced metadata
INSERT INTO chat_messages (chat_id, user_id, message, response, language, ai_model, tokens_used, response_time, confidence_score, context_data, feedback_rating, is_helpful, attachments) VALUES
(1, 1, 'I want to visit Kedarnath temple. What is the best time to go?', 'The best time to visit Kedarnath is from May to October when the temple is open. The weather is pleasant and the trek route is accessible. Avoid monsoon season (July-August) due to heavy rainfall and landslide risks.', 'en', 'llama3.1:8b', 156, 2.3, 0.92, '{"weather_data": "checked", "temple_status": "open_season", "trek_difficulty": "moderate"}', 5, true, null),
(2, 2, 'Can you suggest some beginner yoga poses?', 'Here are some great beginner yoga poses: Mountain Pose (Tadasana), Child''s Pose (Balasana), Downward Dog, and Cat-Cow stretch. Start with these basic poses and hold each for 30 seconds to 1 minute.', 'en', 'llama3.1:8b', 98, 1.8, 0.88, '{"user_level": "beginner", "pose_difficulty": "basic", "safety_checked": true}', 4, true, null),
(3, 3, 'Tell me about traditional Kumaoni folk dances', 'Kumaoni folk dances include Chholiya (sword dance), Jhora (group dance), and Barada Nati. Chholiya is performed during weddings with swords, representing valor and celebration. These dances preserve cultural heritage and community bonding traditions.', 'en', 'llama3.1:8b', 142, 2.1, 0.90, '{"cultural_context": "kumaon_region", "dance_types": "traditional", "cultural_significance": "high"}', 5, true, null),
(4, 4, 'I need emergency contact numbers for Haridwar', 'Here are important emergency contacts for Haridwar: Police: 01334-265308, Hospital (Shri Guru Ram Rai Institute): 01334-286286, Fire Department: 101, Tourist Helpline: 1364. All these services are available 24x7.', 'en', 'llama3.1:8b', 87, 0.9, 0.95, '{"location": "haridwar", "emergency_type": "general", "contacts_verified": true}', 4, true, null),
(5, 5, 'What are the most photogenic places in Uttarakhand?', 'Some of the most photogenic places in Uttarakhand include: Valley of Flowers (alpine flowers), Nainital Lake (reflections), Auli (snow-capped peaks), Rishikesh (Ganga Aarti), Mussoorie (colonial architecture), and Jim Corbett (wildlife photography). Each offers unique photographic opportunities.', 'en', 'llama3.1:8b', 178, 2.5, 0.89, '{"photography_focus": "landscape", "season_considered": "winter", "accessibility": "checked"}', 5, true, null),
(3, 3, 'How can I learn Chholiya dance?', 'You can learn Chholiya dance through cultural workshops in Almora. Master Mohan Singh Rawat offers classes, and there''s an upcoming workshop on March 15-17, 2024. Contact +91-9876543210 for registration. The workshop covers basic steps, sword techniques, and cultural significance.', 'en', 'llama3.1:8b', 134, 1.9, 0.91, '{"workshop_available": true, "instructor_verified": true, "dates_current": true}', 5, true, null),
(1, 1, 'What should I pack for Kedarnath trek?', 'Essential items for Kedarnath trek: warm clothing (layers), waterproof jacket, trekking shoes, first aid kit, torch, power bank, water bottles, energy snacks, sunglasses, sunscreen, and rain cover. Pack light but ensure you have warm clothes for cold nights.', 'en', 'llama3.1:8b', 145, 2.1, 0.93, '{"trek_season": "may", "weather_conditions": "variable", "altitude_considered": true}', 5, true, null),
(2, 2, 'Show me how to do Mountain Pose correctly', 'Mountain Pose (Tadasana): Stand with feet hip-width apart, distribute weight evenly on both feet, engage leg muscles, lengthen spine, relax shoulders away from ears, arms at sides with palms facing forward. Breathe deeply and hold for 1-2 minutes. This pose improves posture and body awareness.', 'en', 'llama3.1:8b', 112, 1.7, 0.94, '{"pose_type": "standing", "difficulty": "beginner", "alignment_cues": "detailed"}', 4, true, null);